=== 03/12/2016 v0.98

- Korrektur, BootMode auf PiGPIO Dämon.
- BootMode auf PiPlus Daemon hinzugefügt (für Tests).
- Sketchs Korrekturen.
- Plugin Korrekturen.
- Verschiedene Verbesserungen.

=== 15/10/2016 v0.97.2

- bootstrapswitch entfernt (Ein/Aus-Tasten) für die Kompatibilität mit Jeedom.
- Mise à jour des visuels de la doc en conséquence.
- verschiedene Korrekturen.
- Arduino/ESP : Envoie de la trame téléinfo au plugin éponyme.

=== 11/10/2016 v0.97

- Redesign und die Verwaltung von Dämonen optimiert.
- Zusätzliche Unterstützung für den Generic Typ (für mobile App) im automatischen oder manuellen Modus.
- Möglichkeit hinzugefügt, virtuelle Befehle automatisch in unterschiedlichen virtuelle zu erstellen, um seine vielfältigen Geräte besser zu verwalten.
- Verschiedene Korrekturen und Verbesserungen am Plugin und Vorbereitung auf das entfernen des Master/Slave-Modus von Jeedom.
Zusatz von System Aktualisierungen (Erforderlich für gpio/dht/DS18B20) beim Installieren der Abhängigkeiten.
- Fixes und Verbesserungen auf die Dämonen (Option hinzugefügt, um zum Beispiel auto-Neustart).
- Verbesserungen der USB, LAN und ESP Sketche:
- Arduino/ESP : Unterstützung für eine serielle Teleinfo Verbindung.
- Arduino/ESP : Unterstützung von LCD-Display-Typ 16x2 für die Nachrichtenübertragung von Jeedom hinzugefügt.
- Arduino/ESP : Unterstützung der persönlichen Sketche für Benutzer (Details in den Sketche) hinzugefügt.
- Arduino/ESP : Pin/Benutzerbefehle (0 bis 100 Max) für Ihre persönliche Sketchs hinzufügt.
- Arduino/ESP : Hinzugefügt wurde die Fähigkeit in den Sketchen bestimmte Funktionen zu aktivieren/deaktivieren, z.B. Platz frei zu machen
- Anpassungen der Option JeedouinoExt (RPI deportiert ohne Jeedom) für fortgeschrittene Benutzer, nur für TESTS.
- Verbesserte Doc
- Zusätzliche neue globale Befehle ALL_SWITCH, ALL_PULSE_LOW, ALL_PULSE_HIGH.

=== 21/06/2016 v0.96

- Verschiedene Plugin und Sketche Korrekturen.
- Abhängigkeiten von Python-DHT et DS18B20 hinzugefügt.
- Unterstützung für die Sonden DHT11, DHT22(AM2302) und DS18B20 für Raspberry PI (piGPIO).
- Unterstützung für HC-SR04-Distanzsensor hinzugefügt.
- Verschiedene Verbesserungen.
- Option JeedouinoExt (RPI deportiert ohne Jeedom) für fortgeschrittene Benutzer, nur für TESTS verbessert.

=== 21/04/2016 v0.95

- Verschiedene Plugin und Dämon Korrekturen.
- zusätzlichen Kontrollen hinzugefügt
- Abhängigkeiten von Python-Serial hinzugefügt.
- Verbesserung der Konfiguration Seite, Registerkarten(Tabs) hinzufügt, für bessere Übersicht.
- Hinweis : Einige Registerkarten und Optionen sind nur im Experten-Modus von Jeedom sichtbar.
- Option JeedouinoExt (RPI deportiert ohne Jeedom) für fortgeschrittene Benutzer, nur für TESTS hinzugefügt.

=== 04/04/2016 v0.94

- Verbesserte Doc.
- Verschiedene Plugin Korrekturen.
- Unterstützung für die IO PiPlus Karte (mit MCP23017)  und seinen Daemon hinzugefügt.
- Verbesserungen auf derJeedom Gesundheits Seite.

=== 21/03/2016 v0.93

- Verbesserte Doc.
- Verschiedene Plugin, Sketchs und Daemon Korrekturen.
- Unterstützung für die NodeMCU Karte hinzugefügt.
- Unterstützung für Docker hinzugefügt (siehe FAQ)

=== 02/03/2016 v0.92

- Verschiedene Plugin und Dämon Korrekturen.
- Ein Reset-Zähler für Arduino/esp-Karten hinzugefügt.
- Einen veränderlichen Digitaleingang (0-255 für 0-10s) für die Karten Arduino/ESP hinzugefügt.

=== 03/02/2016 v0.9

- Verbesserte Doc.
- Verringerung der CPU-Belastung von der Python Daemonen und Verbesserung der Reaktionsfähigkeit.
- verschiedene Korrekturen.
- Hinzugefügt, zusätzliche Überprüfungen/Validierungen.
- Unterstützung für die Sonden DHT(11,21,22) und DS18x20 für Arduinos(Ethernet/USB) und ESP8266.
* (max 1 Sonde pro Pine - kann sich auf die Reaktionsfähigkeit des Arduino auswirken).
- Einen Schieberegler für Pwm Befehle und Wertveränderung im laufenden Betrieb (Szenarien) hinzugefügt.
- Verbesserungen der Plugin-Konfiguration-Seite.

=== 12/01/2016 v0.8

- Verbesserte Doc.
- Allgemeine Verbesserungen der Python-Daemonen.
- Kosmetische Korrekturen.
- Rückgabestatus vom Befehl "Aktion" hinzugefügt.
- Verbesserungen der Arduinos (Ethernet/USB) und ESP8266 Sketche.

=== 07/01/2016 v0.75

- Verbesserte Doc.
- Verbesserte Verwaltung der Dämonen Neustarts, beim Neustart von mehreren Jeedom Slave zur gleichen Zeit.
- Kleinere Korrekturen.

=== 06/01/2016 v0.7

- Kleinere Korrekturen auf die Befehle.
- Fehler behoben, betrifft das piFaces auf piRack.
- Verbesserte Wiederherstellung von Zählerwerten von den Daemonen.
- mehr Flexibilität in der Kommunikation zwischen Sketche/Daemonen und Jeedom hinzugefügt.

=== 03/01/2016 v0.6

- Kleinere Korrekturen.
- Verbesserte Doc.
- Unterstützung für die ESP8266-01 Karte.

=== 01/01/2016

- Fehler behoben im ArduinoUSB Python Daemon
- Kleinere Korrekturen für das Plugin.

=== 31/12/2015

- Bildschirmfotos für den Markt hinzugefügt.

=== 20/12/2015

- Erstellung des Jeedouino Plugins.