=== 15/10/2016 v0.97.2

- Suppression des bootstrapswitch (boutons On/Off) pour compatibilité avec Jeedom.
- Mise à jour des visuels de la doc en conséquence.
- Correctifs divers.
- Arduino/ESP : Envoie de la trame téléinfo au plugin éponyme.

=== 11/10/2016 v0.97

- Refonte et optimisation de la gestion des démons.
- Ajout du support des Generic Type (pour l'app mobile) en mode automatique ou manuel.
- Ajout de la possibilité de créér des commandes virtuelles automatiquement dans différents virtuels afin de mieux gérer ses équipements multiples.
- Correctifs et améliorations diverses sur plugin et préparation à la disparition du mode maître / esclave de Jeedom.
- Ajout de mise à jour du système (nécéssaire pour les gpio/dht/ds18b20) lors de l'installation des dépendances.
- Corréctifs et améliorations sur tous les démons (ajout d'une option de redémarrage automatique par ex).
- Améliorations des sketchs USB, LAN et ESP:
- Arduino/ESP : Ajout du support d'une laison série pour téléinfo.
- Arduino/ESP : Ajout du support d'écran LCD type 16x2 pour envois de messages depuis Jeedom.
- Arduino/ESP : Ajout du support de sketchs perso pour les utilisateurs (détails dans les sketchs).
- Arduino/ESP : Ajout de pins/commandes utilisateur (0 à 100 max) pour vos sketchs perso.
- Arduino/ESP : Ajout de la possibilité dans les sketchs d'activer/désactiver certaines fonctionnalités pour libérer de l'espace par ex..
- Adaptations de l'option JeedouinoExt (RPI déportés sans Jeedom) pour utilisateurs avancés, pour TESTS uniquement.
- Amélioration de la doc
- Ajout de nouvelles commandes globales ALL_SWITCH, ALL_PULSE_LOW, ALL_PULSE_HIGH.

=== 21/06/2016 v0.96

- Correctifs divers sur plugin, et sketchs.
- Ajout des dépendances Python-DHT et DS18B20.
- Ajout du support des sondes DHT 11, 22 (AM2302) et DS18B20 sur Raspberry PI (piGPIO).
- Ajout du support du capteur de distance HC-SR04.
- Améliorations diverses.
- Améliorations de l'option JeedouinoExt (RPI déportés sans Jeedom) pour utilisateurs avancés, pour TESTS uniquement.

=== 21/04/2016 v0.95

- Correctifs divers sur plugin et démons.
- Ajout de vérifications complémentaires.
- Ajout de la dépendance Python-Serial.
- Améliorations de la page configuration avec ajout d'onglets (tabs) pour plus de clarté.
- Note : Certains onglets et options ne sont visibles qu'en mode expert de Jeedom.
- Ajout de l'option JeedouinoExt (RPI déportés sans Jeedom) pour utilisateurs avancés, pour TESTS uniquement.

=== 04/04/2016 v0.94

- Amélioration de la doc.
- Correctifs divers sur plugin.
- Ajout du support de la carte IO PiPlus (et donc des MCP23017) et de son démon.
- Améliorations sur la page santé de Jeedom.

=== 21/03/2016 v0.93

- Amélioration de la doc.
- Correctifs divers sur plugin, sketchs et démons.
- Ajout du support de la carte NodeMCU.
- Ajout du support de Docker ( cf. FAQ )

=== 02/03/2016 v0.92

- Correctifs divers sur plugin et démons.
- Ajout d'un ResetCompteur pour les cartes arduino/esp.
- Ajout d'une entrée digitale variable (0-255 sur 0-10s) pour les cartes arduino/esp.

=== 03/02/2016 v0.9

- Amélioration de la doc.
- Réduction de la charge CPU des démons python, et amélioration de la réactivité.
- Correctifs divers.
- Ajout de vérifications/validations supplémentaires.
- Ajout du support des sondes DHT (11,21,22) et DS18x20 pour les Arduinos (Ethernet/USB) et ESP8266.
* (1 sonde max par pin - peut impacter la réactivité de l'arduino.)
- Ajout d'un slider sur les commandes pwm et changement de valeur à la volée (scenarii).
- Amélioration de la page de configuration du plugin.

=== 12/01/2016 v0.8

- Amélioration de la doc.
- Améliorations globale des démons python.
- Correctifs cosmétiques.
- Ajout du retour d'état des commandes 'action'.
- Amélioration des sketchs Arduinos (Ethernet/USB) et ESP8266.

=== 07/01/2016 v0.75

- Amélioration de la doc.
- Amélioration de la gestion du redémarrage des démons en cas de reboot de plusieurs Jeedom esclaves en même temps.
- Correctifs mineurs.

=== 06/01/2016 v0.7

- Correctifs mineurs sur les commandes.
- Correction d'un bug affectant les piFaces en piRack.
- Amélioration de la récupération des valeurs des compteurs sur les démons.
- Ajout de plus de flexibilité dans la communication entre sketchs/démons et Jeedom.

=== 03/01/2016 v0.6

- Correctifs mineurs.
- Amélioration de la doc.
- Ajout du support de la carte ESP8266-01.

=== 01/01/2016

- Correction d'un bug sur le démon python ArduinoUSB.
- Correctif mineur du plugin.

=== 31/12/2015

- Ajout de screenshots pour le market.

=== 20/12/2015

- Création du plugin Jeedouino.