---
langs: [fr_FR,en_US] 
baseurl: "/"
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
exclude:
- vendor
